name: Shodei CI/CD on Ubuntu
 
on:
  push:
    branches: [ main ]  
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
 
    - name: Test SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: "server ip"
        username: "ubuntu"
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "SSH connection test successful"
 
    - name: Deploy Application to AWS EC2
      uses: appleboy/scp-action@master
      with:
        host: "server ip"
        username: "ubuntu"
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./"
        target: "/mnt/data/var/www/html/script"
        overwrite: true
        rm: true
 
    - name: Copy .env File to Deployment Directory
      uses: appleboy/ssh-action@master
      with:
        host: "server ip"
        username: "ubuntu"
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo cp /home/ubuntu/secret/shodei/.env /mnt/data/var/www/html/script/.env  
 
    - name: Set Correct Permissions
      uses: appleboy/ssh-action@master
      with:
        host: "server ip"
        username: "ubuntu"
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo chown -R www-data:www-data /mnt/data/var/www/html/script/storage
          sudo chmod -R 775 /mnt/data/var/www/html/script/storage
          sudo chmod -R 775 /mnt/data/var/www/html/script/bootstrap/cache
          echo "Permissions set successfully!"
 
    - name: Install Dependencies and Restart Application
      uses: appleboy/ssh-action@master
      with:
        host: "server ip"
        username: "ubuntu"
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /mnt/data/var/www/html/script/
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart nginx
          echo "Deployment complete!"
